# Generated by Django 4.2.5 on 2023-09-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tracking_number", models.CharField(max_length=255)),
                ("carrier", models.CharField(max_length=255)),
                ("sender_address", models.TextField()),
                ("receiver_address", models.TextField()),
                ("article_name", models.CharField(max_length=255)),
                ("article_quantity", models.PositiveIntegerField()),
                ("article_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("SKU", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=255)),
                (
                    "receiver_zip_code",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
    ]
